---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        files: rmc
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args:
          [
            --pretty,
            --show-error-codes,
            --no-strict-optional,
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
          ]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1 # This should be kept in sync with the version in requirements-dev.in
      hooks:
        - id: isort
          args: ["--profile", "black", "--filter-files"]
          files: rmc
